"""ComfyUI's own bookkeeping is not a control the user refused to explain.

``upload`` is a value ComfyUI writes into the API export of an image loader,
and ``control_after_generate`` one it writes beside a seed.  Neither is a
setting anybody chose, so neither could ever be proved safe *or* structural
by the questions this module asks -- and one UNCERTAIN input takes its whole
workflow to ``NEEDS_REVIEW``.  Measured on this repository's own
``example_img2img_api.json``, which is the shape of every img2img, inpaint,
edit and upscale-from-file export there is.

What is **not** broken, and is not touched here: the importer's refusal to
guess at a string it cannot read (T-0054).  The fix is upstream of that rule.

Two guards, each failing on its own -- and each on a *different* mutation:

* **remove the branch** and the verdict tests, the example test and the
  inventory test die, because the two names go back to UNCERTAIN;
* **make the branch match word tokens instead of whole names** and the
  whole-name tests and the unchanged-verdict table die, because ``upload``
  would then reach ``upload_strength`` and ``control`` would reach every
  ``control_*`` a node genuinely offers.  Neither of those is caught by the
  first mutation, and the verdict tests are not caught by the second: a token
  match still returns the same verdict for the two real names.

The last section is the one that says this card changed nothing else: every
verdict in ``UNCHANGED`` was generated by running the **parent commit's**
``semantics.py`` over the same inputs, so it is the old module's own answer
and not something typed from memory.

No graph invented here names a model, a family, a vendor or a node pack,
and nothing in this file was learned from any ComfyUI installation.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Set, Tuple

import pytest

from conftest import EXAMPLES_ROOT
from localcanvas_gateway.workflows import load_registry
from localcanvas_gateway.workflows.sync import (
    HIDDEN_SECTIONS,
    LOCKED_KINDS,
    analyse,
    run_sync,
)
from localcanvas_gateway.workflows.sync import semantics
from localcanvas_gateway.workflows.sync.semantics import (
    BOOKKEEPING_INPUT_NAMES,
    Exposure,
    Verdict,
    classify,
)
from sync_fixtures import SyncWorkspace, write_json

FIXED = datetime(2026, 1, 2, 3, 4, 5, tzinfo=timezone.utc)

def bookkeeping_reason(name: str) -> str:
    """The sentence the new branch composes, for a name it recognises."""

    return (
        "input {!r} is bookkeeping ComfyUI writes into its own API export "
        "beside a widget; nobody chose it, and nothing about what the "
        "workflow generates changes with it.".format(name)
    )


@pytest.fixture()
def workspace(tmp_path: Path) -> SyncWorkspace:
    return SyncWorkspace(tmp_path)


# ==========================================================================
# The verdict itself, whole
# ==========================================================================


def test_the_upload_widget_of_an_image_loader_is_locked() -> None:
    """The whole verdict -- exposure, reason, slug -- not "not uncertain".

    This is the exact pair measured on ``example_img2img_api.json``: ComfyUI
    writes ``"upload": "image"`` into the export of its image loader.
    """

    assert classify("upload", "image") == Verdict(
        Exposure.LOCKED,
        bookkeeping_reason("upload"),
        kind="editor_bookkeeping",
    )


def test_the_widget_beside_a_seed_is_locked() -> None:
    assert classify("control_after_generate", "randomize") == Verdict(
        Exposure.LOCKED,
        bookkeeping_reason("control_after_generate"),
        kind="editor_bookkeeping",
    )


@pytest.mark.parametrize("value", ["fixed", "increment", "decrement", "randomize"])
def test_every_value_that_widget_can_hold_reaches_the_same_verdict(value: str) -> None:
    """The name is the evidence, so the value it happens to carry is not.

    A branch that keyed on the value would pass the test above and fail the
    moment a user's graph was exported with the widget left on ``fixed``.
    """

    assert classify("control_after_generate", value) == Verdict(
        Exposure.LOCKED,
        bookkeeping_reason("control_after_generate"),
        kind="editor_bookkeeping",
    )


def test_a_bookkeeping_name_is_locked_whatever_type_its_value_holds() -> None:
    """The behaviour this card changed beyond the two measured strings.

    The branch is keyed on the input's **name**, so one of these names holding
    a number or a flag is locked as well.  Before this card rule 6 answered
    first for those and exposed them as a field a user could set.  That change
    is the intended semantics of a name-keyed rule -- the name is the whole of
    the evidence, and rule 6 never looks at it -- but it is a real change, and
    a real change with no guard on it is one that rots unnoticed.

    Not vacuous: the numeric and boolean rows of ``UNCHANGED``,
    ``test_the_number_a_user_may_tune_is_still_a_number`` and the
    ``upload_strength``, ``control_scale`` and ``generate_batch`` hazards above
    all say that rule 6 still exposes a number or a flag whose name is *not*
    one of these two -- including three that merely contain a word of one.
    """

    assert classify("upload", 0) == Verdict(
        Exposure.LOCKED,
        bookkeeping_reason("upload"),
        kind="editor_bookkeeping",
    )
    assert classify("control_after_generate", True) == Verdict(
        Exposure.LOCKED,
        bookkeeping_reason("control_after_generate"),
        kind="editor_bookkeeping",
    )


def test_the_slug_is_one_the_frozen_set_knows() -> None:
    """A slug no ``LOCKED_KINDS`` member matches would be a private taxonomy."""

    verdict = classify("upload", "image")

    assert verdict.kind in LOCKED_KINDS
    assert verdict.exposure is Exposure.LOCKED


# ==========================================================================
# Whole names, not word tokens -- the mutation this half exists to kill
# ==========================================================================

#: Inputs a node genuinely offers whose names *contain* a word from the
#: bookkeeping vocabulary.  Every one of them is a control a user may set, and
#: a token match on ``upload``, ``control``, ``after`` or ``generate`` would
#: swallow all four.  Asserted as whole verdicts, so "still not locked" cannot
#: pass by having become something else instead.
TOKEN_HAZARDS = [
    pytest.param(
        "upload_strength",
        0.5,
        Verdict(
            Exposure.EXPOSE,
            "input 'upload_strength' is a number that changes how the workflow "
            "generates.",
            field_type="float",
            role="upload_strength",
        ),
        id="upload-token",
    ),
    pytest.param(
        "control_scale",
        0.9,
        Verdict(
            Exposure.EXPOSE,
            "input 'control_scale' is a number that changes how the workflow "
            "generates.",
            field_type="float",
            role="control_scale",
        ),
        id="control-token-number",
    ),
    pytest.param(
        "control_mode",
        "balanced",
        Verdict(
            Exposure.EXPOSE,
            "input 'control_mode' selects one of the node's own settings.",
            field_type="string",
            role="control_mode",
        ),
        id="control-token-choice",
    ),
    pytest.param(
        "generate_batch",
        4,
        Verdict(
            Exposure.EXPOSE,
            "input 'generate_batch' is a number that changes how the workflow "
            "generates.",
            field_type="integer",
            role="generate_batch",
        ),
        id="generate-token",
    ),
]


@pytest.mark.parametrize("name,value,expected", TOKEN_HAZARDS)
def test_a_control_that_merely_contains_one_of_these_words_is_untouched(
    name: str, value: Any, expected: Verdict
) -> None:
    assert classify(name, value) == expected


def test_the_hazard_names_really_do_contain_the_vocabulary_words() -> None:
    """The fixture check: without it the test above proves nothing.

    If none of those four names shared a word with the vocabulary, a token
    match would leave them alone too and the guard could never fire.
    """

    vocabulary_words: Set[str] = set()
    for entry in BOOKKEEPING_INPUT_NAMES:
        vocabulary_words |= set(entry.split("_"))

    for case in TOKEN_HAZARDS:
        name = case.values[0]
        assert set(name.split("_")) & vocabulary_words, name


def test_the_vocabulary_is_matched_entire_and_case_foldingly() -> None:
    """The same complete name written another way is still that name.

    Normalising case and the character between the words is not a token match
    and must not be read as licence for one: the name is compared whole.
    """

    for spelling in ("upload", "Upload", "UPLOAD"):
        assert classify(spelling, "image").kind == "editor_bookkeeping", spelling
    for spelling in ("control_after_generate", "control-after-generate"):
        assert classify(spelling, "randomize").kind == "editor_bookkeeping", spelling

    # ...and a name that is merely *near* one of them is not one of them.
    assert classify("uploads", "image").kind is None
    assert classify("control_after_generation", "randomize").kind is None


# ==========================================================================
# Where the branch sits: it takes no verdict from a branch above it
# ==========================================================================


def test_the_value_shape_questions_are_still_asked_first() -> None:
    """Placement, proved rather than asserted in a paragraph.

    The branch is after the media question and after both questions about the
    shape of the value.  So an input carrying one of these names *and* a value
    an earlier branch can read is still answered by that earlier branch -- and
    a branch inserted higher up would take those two verdicts away.
    """

    assert classify("upload", "adapter.safetensors") == Verdict(
        Exposure.LOCKED,
        "input 'upload' names a file of weights to load; which file loads is "
        "what the workflow *is*, not how it generates.",
        kind="weights_file",
    )
    assert classify("upload", "C:/somewhere/else/photo.png") == Verdict(
        Exposure.LOCKED,
        "input 'upload' holds a path on this machine; LocalCanvas never puts a "
        "filesystem path in front of a user.",
        kind="filesystem_path",
    )


def test_no_other_vocabulary_in_the_module_claims_these_words() -> None:
    """The other half of the placement claim, and the one that can rot.

    Every branch below the new one asks about the input's *name*, so if one of
    their vocabularies ever gained ``upload``, ``control``, ``after`` or
    ``generate``, the order of the two would start to decide the answer and
    the comment in ``classify()`` would quietly stop being true.  This fails
    the day that happens, which is the day someone would want to know.
    """

    ours: Set[str] = set()
    for entry in BOOKKEEPING_INPUT_NAMES:
        ours |= set(entry.split("_"))

    for label, other in (
        ("LOCKED_ANY_WORDS", semantics.LOCKED_ANY_WORDS),
        ("LOCKED_STRING_WORDS", semantics.LOCKED_STRING_WORDS),
        ("PROMPT_WORDS", semantics.PROMPT_WORDS),
        ("SAFE_STRING_WORDS", semantics.SAFE_STRING_WORDS),
        ("MEDIA_WORDS", semantics.MEDIA_WORDS),
        ("MASK_WORDS", semantics.MASK_WORDS),
    ):
        assert ours & set(other) == set(), label


# ==========================================================================
# The whole graph: the shipped example imports, and produces something
# ==========================================================================


def test_the_shipped_img2img_example_imports_without_needing_review() -> None:
    """The measurement the card was filed on, through the real ``analyse()``.

    The fields are asserted, not merely the absence of the flag: a workflow
    that stops being refused and produces nothing useful is not fixed.
    """

    graph = json.loads(
        (EXAMPLES_ROOT / "example_img2img_api.json").read_text(encoding="utf-8")
    )
    plan = analyse(graph)

    assert plan.problems == ()
    assert plan.needs_review is False
    assert [
        (field.id, field.type, field.section, field.required, field.targets)
        for field in plan.fields
    ] == [
        ("prompt", "multiline", "main", True, (("20", "text"),)),
        ("image", "image", "main", True, (("15", "image"),)),
        ("negative_prompt", "multiline", "advanced", False, (("21", "text"),)),
        ("cfg", "float", "advanced", False, (("40", "cfg"),)),
        ("denoise", "float", "advanced", False, (("40", "denoise"),)),
        ("sampler_name", "string", "advanced", False, (("40", "sampler_name"),)),
        ("scheduler", "string", "advanced", False, (("40", "scheduler"),)),
        ("seed", "integer", "advanced", False, (("40", "seed"),)),
        ("steps", "integer", "advanced", False, (("40", "steps"),)),
    ]


def test_the_example_still_locks_what_it_locked_before() -> None:
    """The other side of the same graph: nothing was let out to buy this.

    The weights the loader names and the prefix the save writes were locked
    before this card and are locked after it, and the bookkeeping widget joins
    them rather than replacing them.
    """

    graph = json.loads(
        (EXAMPLES_ROOT / "example_img2img_api.json").read_text(encoding="utf-8")
    )
    plan = analyse(graph)
    hidden = {
        (item.node, item.input): item.kind
        for item in plan.controls
        if item.section in HIDDEN_SECTIONS
    }

    assert hidden == {
        ("10", "ckpt_name"): "weights_file",
        ("15", "upload"): "editor_bookkeeping",
        ("60", "filename_prefix"): "file_reference",
    }


# ==========================================================================
# Visible in the inventory, absent from the bindings
# ==========================================================================


def bookkeeping_graph() -> Dict[str, Any]:
    """One importable graph carrying both bookkeeping inputs.

    Every node type is invented here.  The picture, the prompt and the two
    numbers are real controls, so the disjointness below is measured against
    a definition that genuinely binds something.
    """

    return {
        "1": {
            "class_type": "ExampleWeightsLoader",
            "inputs": {"ckpt_name": "chosen-weights.safetensors"},
        },
        "2": {
            "class_type": "ExamplePictureLoader",
            "inputs": {"image": "a photo.png", "upload": "image"},
        },
        "3": {
            "class_type": "ExampleTextEncode",
            "inputs": {"text": "a quiet street at dawn", "clip": ["1", 1]},
        },
        "4": {
            "class_type": "ExampleSampler",
            "inputs": {
                "seed": 12345,
                "control_after_generate": "randomize",
                "steps": 24,
                "model": ["1", 0],
                "positive": ["3", 0],
                "pixels": ["2", 0],
            },
        },
        "5": {
            "class_type": "ExampleSave",
            "inputs": {"filename_prefix": "generated", "images": ["4", 0]},
        },
    }


def imported(workspace: SyncWorkspace, graph: Dict[str, Any]):
    folder = workspace.add_source()
    write_json(folder / "one.json", graph)
    workspace.write_config()
    report = run_sync(workspace.load(), now=FIXED)
    registry = load_registry(workspace.repo / "config" / "local" / "workflows")
    return report, registry


def test_bookkeeping_is_reported_with_its_section_slug_and_reason() -> None:
    """T-0069's property: recognised and decided, rather than silently dropped."""

    plan = analyse(bookkeeping_graph())
    entries = {(item.node, item.input): item for item in plan.controls}

    for node, name in (("2", "upload"), ("4", "control_after_generate")):
        target = (node, name)
        entry = entries[target]
        assert entry.section == "locked", target
        assert entry.kind == "editor_bookkeeping", target
        assert entry.reason == bookkeeping_reason(name), target
        assert entry.field is None, target
        assert entry.label is None, target

    assert [
        (item.node, item.input, item.kind)
        for item in plan.not_exposed
        if item.kind == "editor_bookkeeping"
    ] == [
        ("2", "upload", "editor_bookkeeping"),
        ("4", "control_after_generate", "editor_bookkeeping"),
    ]


def test_bookkeeping_never_reaches_a_binding(workspace: SyncWorkspace) -> None:
    """Presence first, then absence, so the absence cannot pass vacuously.

    The two pairs are asserted to be in the inventory as hidden; then the
    definition is asserted to bind something at all; only then is the
    intersection asserted empty.
    """

    _, registry = imported(workspace, bookkeeping_graph())
    plan = analyse(bookkeeping_graph())
    hidden: Set[Tuple[str, str]] = {
        (item.node, item.input)
        for item in plan.controls
        if item.section in HIDDEN_SECTIONS
    }

    assert {("2", "upload"), ("4", "control_after_generate")} <= hidden

    bound = {
        (binding.node, binding.input)
        for workflow in registry.workflows
        for field in workflow.inputs
        for binding in workflow.bindings_for(field.id)
    }
    assert bound == {("2", "image"), ("3", "text"), ("4", "seed"), ("4", "steps")}
    assert bound & hidden == set()


def test_no_bookkeeping_name_or_value_reaches_the_view_the_app_receives(
    workspace: SyncWorkspace,
) -> None:
    """The inventory is a curator's document; the app is served another one."""

    _, registry = imported(workspace, bookkeeping_graph())

    view = json.dumps(registry.workflows[0].detail_view())
    for hidden in ("upload", "control_after_generate", "randomize"):
        assert hidden not in view, hidden


# ==========================================================================
# `model`: the half of the design that was deliberately not done
# ==========================================================================


def test_a_loader_input_naming_a_bare_model_is_still_uncertain() -> None:
    """Not done, and pinned so that "not done" is a decision and not a drift.

    The only bare-model value this repository ever had was
    ``example_video_api.json``'s ``REPLACE_WITH_YOUR_VIDEO_MODEL``, which was
    an artefact of an example file: a real workflow carries a filename and is
    locked by the weights-suffix branch already.  Widening the locked
    vocabulary on that alone would be widening it on nothing, so ``model`` was
    left out -- and the input stays UNCERTAIN, which is the importer's correct
    answer to a string nothing settles.  The example itself was fixed instead
    (T-0081: its placeholder now carries a suffix); the bare string is kept
    here as the shape of value this pins.
    """

    assert classify("model_name", "REPLACE_WITH_YOUR_VIDEO_MODEL").exposure is (
        Exposure.UNCERTAIN
    )
    assert classify("model_name", "a-file.safetensors") == Verdict(
        Exposure.LOCKED,
        "input 'model_name' names a file of weights to load; which file loads "
        "is what the workflow *is*, not how it generates.",
        kind="weights_file",
    )


def test_the_number_a_user_may_tune_is_still_a_number() -> None:
    """``strength_model`` is the tunable ``docs/workflow-schema.md`` insists on.

    Pinned here because it is what the `model` half would have put at risk.
    """

    assert classify("strength_model", 0.8) == Verdict(
        Exposure.EXPOSE,
        "input 'strength_model' is a number that changes how the workflow "
        "generates.",
        field_type="float",
        role="strength_model",
    )


# ==========================================================================
# No existing verdict changed
# ==========================================================================

#: At least one input per branch of ``classify()``, and several for a branch
#: with more than one shape to reach -- 38 rows.  The names are ordinary
#: ComfyUI-shaped ones chosen for the branch each takes; this is **not** an
#: inventory of the literals in the repository's three shipped examples, and
#: it does not claim to be one.  ``model_name`` is the only example literal
#: that happens to appear.  What the table does cover is pinned below by
#: ``test_the_table_above_reaches_every_branch_of_classify``, and the shipped
#: examples are covered whole by the two example tests further up and by
#: ``test_examples.py``.
#:
#: **Generated by running the parent commit's ``semantics.py``**, so each
#: expectation is the old module's own answer -- a table typed by hand would
#: only prove I remembered it.
UNCHANGED = [
    pytest.param(
        "clip",
        ["4", 1],
        Verdict(
            Exposure.UNCERTAIN,
            "input 'clip' holds list, which is not a value a field can carry.",
        ),
    ),
    pytest.param(
        "image",
        "photo.png",
        Verdict(
            Exposure.EXPOSE,
            "input 'image' takes a picture the user supplies.",
            field_type="image",
            role="image",
            media="image",
        ),
    ),
    pytest.param(
        "image",
        "a subfolder/photo.png",
        Verdict(
            Exposure.EXPOSE,
            "input 'image' takes a picture the user supplies.",
            field_type="image",
            role="image",
            media="image",
        ),
    ),
    pytest.param(
        "video",
        "clip.mp4",
        Verdict(
            Exposure.EXPOSE,
            "input 'video' takes a clip the user supplies.",
            field_type="video",
            role="video",
            media="video",
        ),
    ),
    pytest.param(
        "mask",
        "cutout.png",
        Verdict(
            Exposure.EXPOSE,
            "input 'mask' takes a picture the user supplies.",
            field_type="image",
            role="mask",
            media="image",
            mask=True,
        ),
    ),
    pytest.param(
        "images",
        "frame.png",
        Verdict(
            Exposure.EXPOSE,
            "input 'images' takes a picture the user supplies.",
            field_type="image",
            role="images",
            media="image",
        ),
    ),
    pytest.param(
        "filename_prefix",
        "out.png",
        Verdict(
            Exposure.LOCKED,
            "input 'filename_prefix' names a file, a folder or a model to load "
            "('filename').",
            kind="file_reference",
        ),
    ),
    pytest.param(
        "ckpt_name",
        "chosen-weights.safetensors",
        Verdict(
            Exposure.LOCKED,
            "input 'ckpt_name' names a file of weights to load; which file "
            "loads is what the workflow *is*, not how it generates.",
            kind="weights_file",
        ),
    ),
    pytest.param(
        "name",
        "PLACEHOLDER.safetensors",
        Verdict(
            Exposure.LOCKED,
            "input 'name' names a file of weights to load; which file loads is "
            "what the workflow *is*, not how it generates.",
            kind="weights_file",
        ),
    ),
    pytest.param(
        "style_reference",
        "C:/somewhere/else",
        Verdict(
            Exposure.LOCKED,
            "input 'style_reference' holds a path on this machine; LocalCanvas "
            "never puts a filesystem path in front of a user.",
            kind="filesystem_path",
        ),
    ),
    pytest.param(
        "output_dir",
        "renders",
        Verdict(
            Exposure.LOCKED,
            "input 'output_dir' names a file, a folder or a model to load "
            "('dir').",
            kind="file_reference",
        ),
    ),
    pytest.param(
        "device",
        0,
        Verdict(
            Exposure.LOCKED,
            "input 'device' names 'device', which belongs to the machine rather "
            "than to the picture.",
            kind="machine_setting",
        ),
    ),
    pytest.param(
        "debug",
        True,
        Verdict(
            Exposure.LOCKED,
            "input 'debug' names 'debug', which belongs to the machine rather "
            "than to the picture.",
            kind="machine_setting",
        ),
    ),
    pytest.param(
        "lora_name",
        "a-style.safetensors",
        Verdict(
            Exposure.LOCKED,
            "input 'lora_name' names a file of weights to load; which file "
            "loads is what the workflow *is*, not how it generates.",
            kind="weights_file",
        ),
    ),
    pytest.param(
        "text",
        "a quiet street at dawn",
        Verdict(
            Exposure.EXPOSE,
            "input 'text' holds text written in a person's own language.",
            field_type="multiline",
            role="text",
            prompt=True,
        ),
    ),
    pytest.param(
        "text",
        "",
        Verdict(
            Exposure.EXPOSE,
            "input 'text' holds text written in a person's own language.",
            field_type="multiline",
            role="text",
            prompt=True,
        ),
    ),
    pytest.param(
        "negative",
        "blurry",
        Verdict(
            Exposure.EXPOSE,
            "input 'negative' holds text written in a person's own language.",
            field_type="multiline",
            role="negative",
            prompt=True,
        ),
    ),
    pytest.param(
        "seed",
        12345,
        Verdict(
            Exposure.EXPOSE,
            "input 'seed' is a number that changes how the workflow generates.",
            field_type="integer",
            role="seed",
        ),
    ),
    pytest.param(
        "noise_seed",
        9,
        Verdict(
            Exposure.EXPOSE,
            "input 'noise_seed' is a number that changes how the workflow "
            "generates.",
            field_type="integer",
            role="seed",
        ),
    ),
    pytest.param(
        "cfg",
        6.5,
        Verdict(
            Exposure.EXPOSE,
            "input 'cfg' is a number that changes how the workflow generates.",
            field_type="float",
            role="cfg",
        ),
    ),
    pytest.param(
        "steps",
        24,
        Verdict(
            Exposure.EXPOSE,
            "input 'steps' is a number that changes how the workflow generates.",
            field_type="integer",
            role="steps",
        ),
    ),
    pytest.param(
        "denoise",
        0.55,
        Verdict(
            Exposure.EXPOSE,
            "input 'denoise' is a number that changes how the workflow "
            "generates.",
            field_type="float",
            role="denoise",
        ),
    ),
    pytest.param(
        "add_noise",
        True,
        Verdict(
            Exposure.EXPOSE,
            "input 'add_noise' is a flag that changes how the workflow "
            "generates.",
            field_type="boolean",
            role="add_noise",
        ),
    ),
    pytest.param(
        "strength_model",
        0.8,
        Verdict(
            Exposure.EXPOSE,
            "input 'strength_model' is a number that changes how the workflow "
            "generates.",
            field_type="float",
            role="strength_model",
        ),
    ),
    pytest.param(
        "width",
        1024,
        Verdict(
            Exposure.EXPOSE,
            "input 'width' is a number that changes how the workflow generates.",
            field_type="integer",
            role="width",
        ),
    ),
    pytest.param(
        "fps",
        16,
        Verdict(
            Exposure.EXPOSE,
            "input 'fps' is a number that changes how the workflow generates.",
            field_type="integer",
            role="fps",
        ),
    ),
    pytest.param(
        "loop",
        False,
        Verdict(
            Exposure.EXPOSE,
            "input 'loop' is a flag that changes how the workflow generates.",
            field_type="boolean",
            role="loop",
        ),
    ),
    pytest.param(
        "frame_cap",
        48,
        Verdict(
            Exposure.EXPOSE,
            "input 'frame_cap' is a number that changes how the workflow "
            "generates.",
            field_type="integer",
            role="frame_cap",
        ),
    ),
    pytest.param(
        "sampler_name",
        "euler",
        Verdict(
            Exposure.EXPOSE,
            "input 'sampler_name' selects one of the node's own settings.",
            field_type="string",
            role="sampler_name",
        ),
    ),
    pytest.param(
        "scheduler",
        "normal",
        Verdict(
            Exposure.EXPOSE,
            "input 'scheduler' selects one of the node's own settings.",
            field_type="string",
            role="scheduler",
        ),
    ),
    pytest.param(
        "control_mode",
        "balanced",
        Verdict(
            Exposure.EXPOSE,
            "input 'control_mode' selects one of the node's own settings.",
            field_type="string",
            role="control_mode",
        ),
    ),
    pytest.param(
        "control_scale",
        0.9,
        Verdict(
            Exposure.EXPOSE,
            "input 'control_scale' is a number that changes how the workflow "
            "generates.",
            field_type="float",
            role="control_scale",
        ),
    ),
    pytest.param(
        "upload_strength",
        0.5,
        Verdict(
            Exposure.EXPOSE,
            "input 'upload_strength' is a number that changes how the workflow "
            "generates.",
            field_type="float",
            role="upload_strength",
        ),
    ),
    pytest.param(
        "style",
        "PLACEHOLDER",
        Verdict(
            Exposure.UNCERTAIN,
            "input 'style' holds the text 'PLACEHOLDER', and nothing in the "
            "graph says whether that is a setting a user may change or "
            "something structural. It is neither exposed nor dropped: look at "
            "it and decide.",
        ),
    ),
    pytest.param(
        "model_name",
        "REPLACE_WITH_YOUR_VIDEO_MODEL",
        Verdict(
            Exposure.UNCERTAIN,
            "input 'model_name' holds the text "
            "'REPLACE_WITH_YOUR_VIDEO_MODEL', and nothing in the graph says "
            "whether that is a setting a user may change or something "
            "structural. It is neither exposed nor dropped: look at it and "
            "decide.",
        ),
    ),
    pytest.param(
        "motion_strength",
        0.6,
        Verdict(
            Exposure.EXPOSE,
            "input 'motion_strength' is a number that changes how the workflow "
            "generates.",
            field_type="float",
            role="motion_strength",
        ),
    ),
    pytest.param(
        "",
        5,
        Verdict(
            Exposure.UNCERTAIN,
            "input '' has no name this can turn into a field id.",
        ),
    ),
    pytest.param(
        "preset",
        "balanced",
        Verdict(
            Exposure.UNCERTAIN,
            "input 'preset' holds the text 'balanced', and nothing in the graph "
            "says whether that is a setting a user may change or something "
            "structural. It is neither exposed nor dropped: look at it and "
            "decide.",
        ),
    ),
]


@pytest.mark.parametrize("name,value,expected", UNCHANGED)
def test_no_verdict_this_module_already_gave_has_moved(
    name: str, value: Any, expected: Verdict
) -> None:
    assert classify(name, value) == expected


def test_the_table_above_reaches_every_branch_of_classify() -> None:
    """A table that missed a branch would leave that branch unguarded.

    Checked by the shape of the answers rather than by counting rows: every
    exposure, every locking slug the module can return, and both of the two
    ``EXPOSE`` shapes that carry no field id.
    """

    verdicts = [classify(case.values[0], case.values[1]) for case in UNCHANGED]

    assert {verdict.exposure for verdict in verdicts} == set(Exposure)
    assert {verdict.kind for verdict in verdicts if verdict.kind} == {
        "weights_file",
        "filesystem_path",
        "machine_setting",
        "file_reference",
    }
    assert {verdict.field_type for verdict in verdicts if verdict.exposed} == {
        "image",
        "video",
        "multiline",
        "integer",
        "float",
        "boolean",
        "string",
    }
    assert any(verdict.prompt for verdict in verdicts)
    assert any(verdict.mask for verdict in verdicts)


def test_the_new_slug_is_the_only_one_the_frozen_set_gained() -> None:
    """``LOCKED_KINDS`` is a frozen set, written out here in full.

    One member per card that added one, and a card that adds a member has to
    come here and say so -- which is the point of writing the set out rather
    than counting it.  ``technical_media`` is T-0072's; ``load_setting`` is
    T-0100's, and it is the only member that card added.  ``node_shape`` is
    T-0185's, for an input whose declared options are shapes of the node
    rather than values it takes, and it is the only member that card added.
    ``computation`` is T-0218's, for a string on a node whose every declared
    output is a number, and it is the only member that card added.
    ``model_patch`` is T-0241's, for a string on a node whose every declared
    output is a model, and it is the only member that card added.
    ``declared_default`` is T-0244's, for unsettled text saved at exactly the
    default the runtime declares for it, and it is the only member that card
    added.  ``url`` is T-0267's, for a value that is as a whole a web address,
    and it is the only member that card added.  ``model_architecture`` is
    T-0193's, for an input whose name says it chooses the model architecture,
    family or version the workflow is built for, and it is the only member that
    card added.
    """

    assert LOCKED_KINDS == {
        "weights_file",
        "filesystem_path",
        "editor_bookkeeping",
        "machine_setting",
        "file_reference",
        "technical_media",
        "load_setting",
        "node_shape",
        "computation",
        "model_patch",
        "declared_default",
        "url",
        "model_architecture",
    }
